server:
  port: 8082
  servlet:
    context-path: /pagamento
    
spring:
  application:
    name: pagamento
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibenate:
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  jmx:
    enabled: false
  datasource:
    url: jdbc:mysql://localhost:3306/pagamento
    username: root
    password: 123456
    
  rabbitmq: 
    host: localhost
    port: 5672
    username: admin
    password: admin
    
crud:
  rabbitmq:
    exchange: crud.exchange
    queue: crud.produto.queue    