server:
  port: 8082
  servlet:
    context-path: /pagamento
    
spring:
  application:
    name: pagamento
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibenate:
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  jmx:
    enabled: false
  datasource:
    url: jdbc:mysql://localhost:3306/pagamento
    username: inova
    password: 123mudar