server:
  port: 8081
  servlet:
    context-path: /crud
    
spring:
  application:
    name: crud
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibenate:
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  jmx:
    enabled: false
  datasource:
    url: jdbc:mysql://localhost:3306/crud
    username: root
    password: 123456
  